version: '3'
services:
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    restart: always
    ports:
      - '3050:80'
  mongo-server:
    image: mongo
    restart: always
  redis-server:
    image: redis
    restart: always
  api:
    build:
      dockerfile: Dockerfile.dev
      context: DevConnect-chat-server
    volumes:
      - /app/node_modules
      - ./DevConnect-chat-server:/app
    environment:
      - CHATKIT_KEY=9afdfeff-5567-44d3-a4f7-1151f41f3b9c:oNwWBHRK1qrpXjZBMQmyw0I1iSg/l34bhLEI9AU6/2w=
      - PORT=5000
      - MONGO_HOST=mongo-server
      - MONGO_PORT=27017
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - INSTANCE_CHATKIT=v1:us1:3dd62a71-d604-4985-bbb9-5965ea8bb128
      - MONGO_URI=mongodb://production:elanzo07@ds143893.mlab.com:43893/chatkit-prod
      - PM2_PUBLIC_KEY=1v03n1o6n82vqy9
      - PM2_SECRET_KEY=f98xzodv3lgc043
      - SECRET_OR_KEY=HELLOFROMTHEOTHERSIDE
      - SENTRY_URI=https://22778aac214b4d149277d423c4f558b3@sentry.io/1405954
  client:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app

